import React from 'react';
import { ArrowLeft } from 'lucide-react';

const termsAndConditionsLines = [
  'TokenMetr Legal',
  '',
  '1. Acceptance of Terms',
  '',
  'By using TokenMetr, you agree to these Terms and Conditions.',
  '',
  '2. Description of Service',
  '',
  'TokenMetr provides:',
  '',
  'The service is designed to enhance interactions with AI systems.',
  '',
  '- Prompt optimization',
  '- Token reduction',
  '- Prompt improvement and structuring',
  '',
  '3. User Responsibilities',
  '',
  'You agree to:',
  '',
  '- Use the service lawfully',
  '- Not submit harmful, illegal, or sensitive content',
  '- Not misuse or attempt to exploit the system',
  '',
  '4. AI-Generated Output Disclaimer',
  '',
  '- Outputs are generated by AI and may not always be accurate.',
  '- Users are responsible for reviewing and validating outputs before use.',
  '- TokenMetr does not guarantee correctness or completeness.',
  '',
  '5. Data Usage',
  '',
  'By using TokenMetr:',
  '',
  '- You consent to prompt processing via third-party AI services.',
  '- You understand that data may be transmitted to external APIs for functionality.',
  '',
  '6. Intellectual Property',
  '',
  '- The platform, design, and features of TokenMetr are owned by us.',
  '- Users retain ownership of their input prompts.',
  '',
  '7. Limitation of Liability',
  '',
  'TokenMetr is provided "as is":',
  '',
  '- We are not liable for any damages resulting from use of the service.',
  '- We do not guarantee uninterrupted or error-free operation.',
  '',
  '8. Service Modifications',
  '',
  'We may:',
  '',
  '- Modify or discontinue features',
  '- Update functionality without prior notice',
  '',
  '9. Termination',
  '',
  'We reserve the right to suspend or terminate access if:',
  '',
  '- Terms are violated',
  '- Misuse is detected',
  '',
  '10. Changes to Terms',
  '',
  'We may update these terms periodically. Continued use implies acceptance.',
  '',
  '11. Governing Law',
  '',
  'These terms are governed by applicable laws in your jurisdiction.',
  '',
  '12. Contact',
  '',
  '- arpit@developerbazaar.com',
];

export function TermsAndConditionsPage() {
  const goHome = () => {
    window.history.pushState({}, '', '/');
    window.dispatchEvent(new PopStateEvent('popstate'));
  };

  const renderLine = (line: string, index: number) => {
    if (line === '') {
      return <div key={`spacer-${index}`} style={{ height: '10px' }} />;
    }

    if (line === 'TokenMetr Legal') {
      return (
        <h1
          key={`title-${index}`}
          style={{
            margin: '0 0 8px 0',
            fontFamily: 'Sora, sans-serif',
            fontSize: 'clamp(28px, 4vw, 38px)',
            lineHeight: 1.2,
            color: '#1A1A1A',
          }}
        >
          {line}
        </h1>
      );
    }

    if (/^\d+\./.test(line)) {
      return (
        <h2
          key={`section-${index}`}
          style={{
            margin: '12px 0 0 0',
            fontFamily: 'Sora, sans-serif',
            fontSize: '20px',
            lineHeight: 1.35,
            color: '#1F2937',
          }}
        >
          {line}
        </h2>
      );
    }

    return (
      <p
        key={`line-${index}`}
        style={{
          margin: 0,
          fontFamily: 'DM Sans, sans-serif',
          fontSize: '15px',
          lineHeight: 1.75,
          color: '#374151',
        }}
      >
        {line}
      </p>
    );
  };

  return (
    <section
      style={{
        background: 'linear-gradient(180deg, #FDFCFA 0%, #FAF7F3 100%)',
        minHeight: 'calc(100vh - 64px)',
        padding: '72px 24px',
      }}
    >
      <div style={{ maxWidth: '980px', margin: '0 auto' }}>
        <button
          onClick={goHome}
          style={{
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            fontFamily: 'DM Sans, sans-serif',
            color: '#6B7280',
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
            marginBottom: '16px',
            padding: 0,
            fontSize: '14px',
          }}
        >
          <ArrowLeft size={16} /> Back to Home
        </button>
        <div
          style={{
            background: '#FFFFFF',
            border: '1px solid #E5E3DF',
            borderRadius: '16px',
            padding: '32px',
            boxShadow: '0 20px 45px rgba(0,0,0,0.06)',
          }}
        >
          {termsAndConditionsLines.map((line, index) => renderLine(line, index))}
        </div>
      </div>
    </section>
  );
}
